### ISSUE TITLE
Finding data storage options for storing Genomic data

### ISSUE THREAD

**Issue by ShivamJoshi31** [professor-greebie/SENG8080-2-field_project#104]
According, after going through the CSV file,  it seems that the best option to store this data is in Mongo DB.  It is a document oriented database , so it is flexible and uses JSON like documents. Also it will allow us to keep the schema capabilities flexible. This tool also provide horizontal scalability .  If one want to query data, its easy in mongo as it has various types of indexes.

**Comment by ShivamJoshi31** [comment]
Other then Mongo, we can also consider some Big Data technologies like distributed file systems which include Hadoop and hive. Here , large amount of data is stored across multiple servers. It allow us with fault tolerance, high scalability, parallel processing capabilities which can be helpful for our genomic dataset .

**Comment by nayan-prajapati** [comment]
Agreed with Shivam about both options (MongoDB and Hive (Hadoop)). Discussed with Shivam options, possibilities, and solutions and decided that I and Varun are going to help him with data storage and maintenance.

**Comment by nayan-prajapati** [comment]
We are going with the Hadoop option. 

Discussed with @professor-greebie in class.

Will create another issue for the docker image of Hadoop.
