### ISSUE TITLE
Choosing Tools for Data Analysis and Visualization

### ISSUE THREAD

**Issue by devanshijoshi09** [professor-greebie/SENG8080-2-field_project#116]
We have to decide which tool to be used for data analysis and visualization.
We can use Jupyter Notebook for analysis and Tableau for visualizations 
Any suggestions?

**Comment by nicolechanky** [comment]
I think it's a good suggestion of using Tableau for data visualization and Python for the data analysis as they are more practical and common in the market

**Comment by nicolechanky** [comment]
Discussed in class and good to use both Python and Tableau.
