### ISSUE TITLE
Genomic data summary

### ISSUE THREAD

**Issue by nicolechanky** [professor-greebie/SENG8080-2-field_project#118]
As we want to understand the genomic data, can anyone in the documentation team provide the description? For example, including but not limited to, what does the column about and type of data etc.

**Comment by nicolechanky** [comment]
Pass to data research team to handle the issue

**Comment by devanshijoshi09** [comment]
Hey Nicole. The Data Research Issue #96 contains the csv file and the documentation file for the data. The file was not uploaded to the code base nor was the CSV file uploaded in the code base. I am attaching the links in this thread.
.CSV files for the main gene transcript

Kangaroo rat dataset .csv file format:
[kangaroo rat.zip](https://github.com/professor-greebie/SENG8080-2-field_project/files/11789976/kangaroo.rat.zip)

Rat dataset .csv file format:
[Rat.zip](https://github.com/professor-greebie/SENG8080-2-field_project/files/11789981/Rat.zip)

Documentation of datasets:
[Data Definition.docx](https://github.com/professor-greebie/SENG8080-2-field_project/files/11789966/Data.Definition.docx)

**Comment by nicolechanky** [comment]
Thanks Devanshi for the information provided. As discussed during the class before and per my understanding, the dataset are supposed to be dogs, cats and human genomic data, may I know why there are kangaroo, and rat .csv file instead?

**Comment by deep1305** [comment]
Thanks Nicole for asking.  Kangaroo and Rat are interesting animals to study from a genomic perspective. the Kangaroo and Rat .csv files contain gene expression data from two different tissues: liver and kidney. Kangaroos are marsupials, which have a different reproductive system than placental mammals, such as humans and dogs. Rats are rodents, which have a high metabolic rate and can adapt to various environments. By comparing the gene expression patterns of these animals across different tissues, we can learn more about their physiology and evolution. This was the reason we as a data research team decided to go further with this choices.
