### ISSUE TITLE
Data Cleaning Progress

### ISSUE THREAD

**Issue by devanshijoshi09** [professor-greebie/SENG8080-2-field_project#119]
As the script to get the data has already been posted. I am requesting an update on the data quality team's progress and approach for data cleaning to ensure reliable and accurate data for analysis tasks.

**Comment by rubelbinu** [comment]
@devanshijoshi09 - Initial data cleaning is done. We have added the data cleaning code and csv file in the data quality folder.

@sachinjoseph26 @Jags26 @theoneiros @Rony0481 - Please can you guys check if any other things need to be done the data uploaded now. 

Thanks

**Comment by devanshijoshi09** [comment]
@rubelbinu Thank you for the update
