### ISSUE TITLE
Collect Genomic Data from S3

### ISSUE THREAD

**Issue by professor-greebie** [professor-greebie/SENG8080-2-field_project#2]
To begin our process, we will need some data. The Data Collection group can use boto3 to download the data that we need. They may need to consult with the Data Research team to decide what kinds of data would be useful.

**Comment by professor-greebie** [comment]
We will collect dog, cat and human data to determine which humans are most likely to prefer cats vs dogs.

**Comment by professor-greebie** [comment]
- Genome Browser site:  https://hgdownload.soe.ucsc.edu/downloads.html
- AWS Marketplace url: https://aws.amazon.com/marketplace/pp/prodview-zwa76yrp5etou?sr=0-2&ref_=beagle&applicationId=AWSMPContessa#overview

**Comment by ShivamJoshi31** [comment]
Rat and Kangaroo Dataset is already collected. Lets go for further process !!
