### ISSUE TITLE
Data Research

### ISSUE THREAD

**Issue by sharathchandragoli** [professor-greebie/SENG8080-2-field_project#96]
Identify which files will be helpful or contains data of genes for rat and kangaroo rat

**Comment by sharathchandragoli** [comment]
GTF files for the main gene transcript

kangaroo rat
https://hgdownload.soe.ucsc.edu/goldenPath/dipOrd1/bigZips/genes/

rat
https://hgdownload.soe.ucsc.edu/goldenPath/rn7/bigZips/genes/

**Comment by chiragmb** [comment]
looks good to me
